#!/usr/bin/bash

FILE=$1

while read -r NUMBERS; do
    factors=($(factor "$NUMBERS"))
    if [ ${#factors[@]} -eq 2 ]; then
        echo "$NUMBERS is prime"
    else
        largest_factor=${factors[-1]}
        second_largest_factor=$(($NUMBERS / $largest_factor))
        echo "$NUMBERS=$second_largest_factor*$largest_factor"
    fi
done < "$FILE"
